language: java
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - publican
      - python-lxml

deploy:
  - provider: script
    skip_cleanup: true
    script: .travis/deploy_on_gh_pages.sh master
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: .travis/deploy_on_gh_pages.sh tagged
    on:
      tags: true
